name: Build Firmware

on: [push, pull_request]

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get install arduino-mk
#    - name: Prepare
#      run: |
#        export ARDMK_DIR=$(dirname $(find /usr -name Arduino.mk))
#        export ARDUINO_DIR=$ARDMK_DIR
    - name: Build
      run: |
        ./build.sh
        ls build
    - name: Archive Build
      uses: actions/upload-artifact@v3
      with:
        name: firmware hex files
        path: build/*.hex